### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by hillmark** [EricLambrecht/react-timing-hooks#26]
Is there a plan to support react 18?

`npm i react-timing-hooks`

Throws

`Could not resolve dependency: react@"^16.8.0 || ^17.0.0" from react-timing-hooks@2.2.3`

Looks like a nifty little library, thanks!

**Comment by EricLambrecht** [comment]
Hey @hillmark ,

thank you for mentioning it and sorry for taking so long to respond, I was quite busy the last few months unfortunately.

I definitely want to support React 18. It should probably work already, but of course I'll have to test it first and then update the package accordingly. I will try to do that soon! – but also feel free to open a PR of course, if you want to. 😁

**Comment by EricLambrecht** [comment]
React 18 is now supported (in version 3.0.0).

I am very sorry it took so long, had a lot on my plate recently.
