### ISSUE TITLE
Manual clearTimeout for `useTimeout`? 

### ISSUE THREAD

**Issue by benkeen** [EricLambrecht/react-timing-hooks#28]
Hey @EricLambrecht! 

How do you _manually_ cancel a timeout created by useTimeout? I have a scenario where I have specific logic. Didn't see a reference to the native setTimeout response, so not sure it's possible. It looks like we just need to return the ID here, then also handle clearing the return value after the timeout it complete, internally in that component.
https://github.com/EricLambrecht/react-timing-hooks/blob/master/src/timeout/useTimeout.ts#L30 

Thanks!

**Comment by EricLambrecht** [comment]
Hey @benkeen ,

thanks for your question, and sorry that it took me so long to answer, I had a lot on my plate recently. 

You are right, there is currently no way to manually cancel a timeout. However, I like the idea and I will try to implement it. I think it's a very useful feature indeed.

**Comment by EricLambrecht** [comment]
This feature has now been added in version 3.1.0

**Comment by benkeen** [comment]
Thanks @EricLambrecht!
