### ISSUE TITLE
"Stop"-function does not reset timer

### ISSUE THREAD

**Issue by megasus** [EricLambrecht/react-timing-hooks#36]
**Bug Description:**

Hey there!
Maybe I am missing something, but shouldn't I be able to reset the timer by using the provided Stop function of IntervalControls?

**To Reproduce:**
Minimal example here:
https://playcode.io/1954849

**Expected behavior:**
I start the timer by calling start(), the timer starts ticking as expected.
I stop the timer by calling stop(), the timer should halt and reset to its initial value (0).
Alternatively it could also reset on start() after the timer has previously been stopped, which is currently also not the case.

**System:**
- Node Version: 18.12.1
- OS: Windows 11
- Browser: chrome 127

**Comment by EricLambrecht** [comment]
Hey there @megasus ,

thank you for opening this bug ticket! I agree with you, that it is quite counter intuitive that the timer does not reset on stop. 

As of now, the difference between stop and pause was only that the underlying interval was destroyed (on stop) or not (on pause). But like I said, I agree with you, that this is not what you expect from a counter, so I will change this in the next version (today or tomorrow probably!).

**Comment by EricLambrecht** [comment]
Hey @megasus ,

this should've been fixed in the new version `5.0.0`.
